[project]
name = "pip_test"
description = "Prove pyproject.toml files"
version = "0.1.0"
authors = [
    { name = "Antonio German Marquez Trujillo", email = "germanoctako@gmail.com" }
]
dependencies = [
    "urllib3>=2.0.2",
    "Jinja2>=3.1.5",
    "itsdangerous>=2.1.2",
    "click>=8.1.3",
    "blinker>=1.6.2",
    "importlib-metadata>=3.6.0; python_version < '3.10'"
]

[project.optional-dependencies]
dev = [
    "tox",
    "pre-commit",
    "bump2version"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
